# 2 - build Unbound
name: CD 20 Build Unbound Docker Image
   
on:   
  workflow_run:
    workflows:
      - CD 10 Unbound and OpenSSL Build Environement Release
      - CD 11 Force new build on manual dispatch
    types:
      - completed

jobs:
  buildvars:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      BUILD_DATE: ${{ steps.IMPORT_BUILDVARS.outputs.BUILD_DATE }}
      UNBOUND_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.UNBOUND_VERSION }}
      OPENSSL_DOCKERBUILDENV_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.OPENSSL_DOCKERBUILDENV_VERSION }}
      DOCKER_IMAGE_VERSION: ${{ steps.IMPORT_BUILDVARS.outputs.DOCKER_IMAGE_VERSION }}
    
    steps:             
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    
    - name: Import build variables from buildvars file
      id: IMPORT_BUILDVARS
      run: |
        cat buildvars | grep BUILD_DATE >> $GITHUB_OUTPUT
        cat buildvars | grep UNBOUND_VERSION >> $GITHUB_OUTPUT
        cat buildvars | grep OPENSSL_DOCKERBUILDENV_VERSION >> $GITHUB_OUTPUT
        cat buildvars | grep DOCKER_IMAGE_VERSION >> $GITHUB_OUTPUT

  unbound-build: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
          - platform: linux/arm/v7
            runner: ubuntu-24.04-arm
          - platform: linux/arm/v6
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    needs: buildvars
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "BUILDPLATFORM=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout source
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        env:
          DOCKERHUB_SLUG: "megavolts/unbound"
        with:
          platforms: ${{ matrix.platform }}
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            BUILD_DATE=${{ needs.buildvars.outputs.BUILD_DATE }}  
            UNBOUND_VERSION=${{ needs.buildvars.outputs.UNBOUND_VERSION }}  
            DOCKER_IMAGE_VERSION=${{ needs.buildvars.outputs.DOCKER_IMAGE_VERSION }}
            OPENSSL_DOCKERBUILDENV_VERSION=${{ needs.buildvars.outputs.OPENSSL_DOCKERBUILDENV_VERSION }}
          file: ./unbound/Dockerfile   
          context: ./unbound/
          push: ${{ github.event_name != 'pull_request' }}
          sbom: ${{ github.event_name != 'pull_request' }}
          provenance: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:${{ needs.buildvars.outputs.DOCKER_IMAGE_VERSION }}   
            ${{ env.DOCKERHUB_SLUG }}:latest
    
